# Generated by Django 6.0.3 on 2026-03-14 13:09

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('author', 'นักเขียน'), ('user', 'ผู้ใช้ทั่วไป'), ('admin', 'ผู้ดูแลระบบ')], default='user', max_length=20)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('idcard', models.CharField(blank=True, max_length=20, null=True)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='eBook',
            fields=[
                ('ebookid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('computer', 'คอมพิวเตอร์'), ('data_science', 'วิทยาศาสตร์ข้อมูล'), ('computer_engineering', 'วิศวกรรมคอมพิวเตอร์')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('ebook_description', models.TextField()),
                ('cover', models.ImageField(upload_to='covers/')),
                ('ebooksample', models.FileField(upload_to='samples/')),
                ('ebooktoken', models.IntegerField()),
                ('publishdate', models.DateField()),
                ('page', models.IntegerField()),
                ('poststatus', models.CharField(choices=[('Publish', 'Publish'), ('Unpublish', 'Unpublish')], default='Unpublish', max_length=20)),
                ('tag', models.CharField(help_text='คั่นด้วยลูกน้ำ (comma)', max_length=255)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'author'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagenumber', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('ebookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marketshare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('page', models.IntegerField()),
                ('uread', models.IntegerField(default=0)),
                ('ebookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ebook')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymenttype', models.CharField(choices=[('paysubscription', 'ชำระค่าสมัคร'), ('payebook', 'ชำระโทเค็น')], max_length=20)),
                ('subprice', models.IntegerField(default=1999)),
                ('tokenpaid', models.IntegerField(default=0)),
                ('transdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('wait', 'รอตรวจสอบ'), ('received', 'ตรวจสอบแล้ว (Received)')], default='wait', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidtype', models.CharField(choices=[('paysubscription', 'จ่ายค่าสมัคร'), ('payebook', 'จ่ายโทเค็นซื้อหนังสือ'), ('sellebook', 'รับโทเค็น (ขายหนังสือได้)')], max_length=20)),
                ('paidtoken', models.IntegerField(default=0)),
                ('gettoken', models.IntegerField(default=0)),
                ('tokenbalance', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('ebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ebook')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
