# Generated by Django 6.0.3 on 2026-03-27 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)])),
                ('token', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ebook',
            name='purchased_users',
            field=models.ManyToManyField(blank=True, related_name='purchased_ebooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='author_expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='token_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 'author'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_ebooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymenttype',
            field=models.CharField(choices=[('subscription', 'สมัครนักเขียน'), ('topup', 'เติม token')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('wait', 'รอตรวจสอบ'), ('received', 'ตรวจสอบแล้ว (Received)'), ('rejected', 'ยกเลิก')], default='wait', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccount',
            name='paidtype',
            field=models.CharField(choices=[('subscription', 'สมัครนักเขียน'), ('topup', 'เติม token'), ('buy', 'ซื้อ ebook'), ('sell', 'ขาย ebook')], max_length=20),
        ),
    ]
