# Generated by Django 6.0.3 on 2026-03-28 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaccount_transdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccount',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaccount',
            name='paidtype',
            field=models.CharField(choices=[('paysubscription', 'จ่ายค่าสมัคร'), ('payebook', 'จ่ายโทเค็นซื้อหนังสือ'), ('sellebook', 'รับโทเค็น (ขายหนังสือได้)'), ('topup', 'เติมโทเค็น')], max_length=20),
        ),
    ]
