# Generated by Django 6.0.3 on 2026-03-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transaccount_create_at_alter_transaccount_paidtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccount',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
