# Generated by Django 6.0.3 on 2026-03-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_topupplan_ebook_purchased_users_and_more'),
        ('app', '0004_rename_create_at_transaccount_created_at'),
    ]

    operations = []
